### ISSUE TITLE
Resolve (MS-Windows) unit test issues.

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#1984]
This is an umbrella issue/task for resolving problems with unit tests that are currently manifesting (mostly) under MS-Windows.

There are at least two existing issues that I believe are related to this task:

* Issue #840 - Unit tests that test NIO are flaky
* Issue #1549 - network abstraction tests issues

Now that we are able to run tests under Windows via Github Actions, it should be much easier to solve all the Windows-related testing problems. I believe there are (or were) related intermittent failures that can occur on macOS or Linux.

I believe the solution is non-trivial and will be broken down into a handful of sub-issues and will require multiple Pull Requests to resolve. This issue should remain open until we have all tests working reliable under Windows and Windows tests activated (re-activated) in the Github Actions test configuration file(s).

**Comment by msgilligan** [comment]
**Action Plan**

- [x] Add unit tests under Windows on CI.
- [ ] Disable Windows unit tests until issues are resolved
- [ ] Fix Windows and intermittent unit-test failures
- [ ] Re-enable Windows unit tests.

This _comment_ will be updated as plans change and new information is discovered.

**Comment by msgilligan** [comment]
I have a handful of ideas for how we can approach this and various subtasks that may be helpful:

1. Separate unit tests from integration tests (see [Configuring integration tests](https://docs.gradle.org/current/userguide/java_testing.html#sec:configuring_java_integration_tests))
1. Replace (or supplement) integration tests with true unit tests that test the same thing only faster and more reliably. Doing this may require creating test fixtures, creating mocks, adding a mocking library, etc.
1. Re-enable excluded tests `PeerTest*`, `TransactionBroadcastTest*`, `DnsDiscoveryTest*` once we figure out how to run them properly/reliably.
1. Not directly related to the main issue, but while we're considering test environment improvements it would be nice to add a CI job that runs the tests in an Android environment.
1. Consider Upgrading to JUnit 5 (see [Using JUnit 5 with Gradle](https://www.baeldung.com/junit-5-gradle) and [Android Unit Testing with JUnit5](https://medium.com/@boonkeat/android-unit-testing-with-junit5-d1b8f9c620b6))
1. Consider using Spock Framework -- it has powerful Mocking capabilities and a very expressive DSL for tests. (One downside is it doesn't work in the Android environment)
1. Consider using Kotlin language tests and tools.  This may offer some of the expressiveness of Groovy/Spock but still run in the Android environment.

**Comment by schildbach** [comment]
I generally like these ideas! On the topic of Spock vs. Kotlin I'd lean towards Kotlin – it's something I wanted to try out myself for tests anyway.

You've probably noticed by now this is a huge undertaking. We've got tons of unit tests and they have saved our asses multiple times already! But this also means it's a lot of stuff to untangle and convert into whatever new language or frameworks we use.

**Comment by msgilligan** [comment]
>On the topic of Spock vs. Kotlin I'd lean towards Kotlin

Me, too. Because Android.
This might be helpful: [Best Practices for Unit Testing in Kotlin](https://phauer.com/2018/best-practices-unit-testing-kotlin/)

> You've probably noticed by now this is a huge undertaking. We've got tons of unit tests and they have saved our asses multiple times already! But this also means it's a lot of stuff to untangle and convert into whatever new language or frameworks we use.

Yes, it has to be a gradual migration.

**Comment by msgilligan** [comment]
PR #2022 (An upgrade to JUnit Platform with the "Vintage" test engine) would be a fist step in a gradual migration to newer tests and testing tools.

**Comment by msgilligan** [comment]
So, in recent PRs some of the tests running under Linux in Github Actions have started failing. It appears these are the same tests, with the same error (`java.lang.RuntimeException: org.bitcoinj.core.VerificationException: Block too far in future: 2020-08-19T23:45:06Z (1597880706) vs allowed 2020-08-19T00:21:58Z (1597796518)`) that we were seeing under Windows.

I created PR #2023 which allow us to download the test results (.xml) and test reports (.html) of failed (and successful) jobs. It shows the following tests are failing:

```
H2FullPrunedBlockChainTest. missingHeightFromCoinbase
H2FullPrunedBlockChainTest. skipScripts
H2FullPrunedBlockChainTest. testFinalizedBlocks
H2FullPrunedBlockChainTest. testGeneratedChain
H2FullPrunedBlockChainTest. testGetOpenTransactionOutputs
H2FullPrunedBlockChainTest. testUTXOProviderWithWallet
LevelDBFullPrunedBlockChainTest. missingHeightFromCoinbase
LevelDBFullPrunedBlockChainTest. skipScripts
LevelDBFullPrunedBlockChainTest. testFinalizedBlocks
LevelDBFullPrunedBlockChainTest. testGeneratedChain
LevelDBFullPrunedBlockChainTest. testGetOpenTransactionOutputs
LevelDBFullPrunedBlockChainTest. testUTXOProviderWithWallet
MemoryFullPrunedBlockChainTest. missingHeightFromCoinbase
MemoryFullPrunedBlockChainTest. skipScripts
MemoryFullPrunedBlockChainTest. testFinalizedBlocks
MemoryFullPrunedBlockChainTest. testGeneratedChain
MemoryFullPrunedBlockChainTest. testGetOpenTransactionOutputs
MemoryFullPrunedBlockChainTest. testUTXOProviderWithWallet
```

It is the same 6 tests failing under 3 different configurations (H2, LevelDB, Memory.) We should take a closer look at these tests to see if we can "fix" them. We should also consider configuring them as ignored until we can fix them.

**Comment by msgilligan** [comment]
> We should also consider configuring them as ignored until we can fix them.

I gave that a try and it didn't work. Interestingly, it caused the "Block too far in the future" problem to move to other tests.

**Comment by schildbach** [comment]
That's weird. Can we see the time and timezone for the start of all tests? I suspect some jump there.

**Comment by msgilligan** [comment]
I'll take a look at that.

**Comment by msgilligan** [comment]
It looks like the problems are being caused by some unit test hooks in the code for mocking time. I have fixed all the problems, but want to review my fixes and clean them up (I think I changed more than necessary). I should be able to submit a PR with the fixes in the next couple of days.

I also think we should review these hooks when we move to JUnit 5. And, as these tests are integration tests, I recommend moving them out of `core` and into a new module called `core-integration` (or similar) so that we can require newer Gradle and JDK 8 to run them. This will allow us to begin the cleanup right away but still create Debian builds with Gradle 4.1.x

**Comment by msgilligan** [comment]
OK, the Windows tests are now running and merged into the `master` branch.  (We still have Issue #2032 outstanding)

@schildbach In this issue (particularly in [this](https://github.com/bitcoinj/bitcoinj/issues/1984#issuecomment-619239187) comment) we talk about a longer-term strategy for improving unit tests.  Should we:

(a) rename this issue to something like "refactor/improve unit and integration tests"
(b) close this issue and open a new one for that purpose
(c) something else

**Comment by msgilligan** [comment]
PR #2036  implements #1, #5, and #7 as discussed above. It creates a separate subproject for `integtest` so we can use JUnit 5 without requiring a newer Gradle to build `core`.

**Comment by msgilligan** [comment]
>Should we:
> 
> (a) rename this issue to something like "refactor/improve unit and integration tests"
> (b) close this issue and open a new one for that purpose
> (c) something else

@schildbach I just chose (a) (I think we have a good thread going here about fixing the longer-term issues, so let's keep it going.

**Comment by msgilligan** [comment]
@schildbach continuing the discussion of "what belongs in the new integration-test/junit5 subproject" here...

So the main idea of PR #2036 was to create a place where we can begin writing tests with JUnit 5 and Kotlin. Because of the Debian situation we can't do it in the `core` subproject, so I created a new sibling project for `core` where we can put tests. This will allow us to have a Debian-package-only build that will build `bitcoinj-core.jar` but won't run _all_ tests.

Here are a few thoughts/points to keep in mind as we approach this:

* Neither of us (@msgilligan or @schildbach) have much experience with JUnit 5 and Kotlin tests (right?) so we're going to be learning as we go along. (Hopefully other contributors will emerge who have more experience with these tools...)
* Within the new subproject (whatever we name it and whatever we decide "belongs" there) we have the ability to create multiple test "source sets" (or classpaths or source directories) so that is _one_ method we can create subsets of the JUnit 5 tests.
* Within each source set/directory we have the ability to organize the tests into a Java package structure (a 2nd method of creating subcategories of tests)
* We have the ability to create flags or tags that can enable or disable certain cross-cutting categories of tests within a given test "run" (a 3rd method of creating subcategories of tests)
* True unit tests will definitely need to be in the same Java package (e.g. `org.bitcoinj.utils`) as the classes/methods they test.
* Integration tests (which generally won't be accessing package-private methods or fields) can have their own Java package structure (e.g. `org.bitcoinj.core.integration.network` or `org.bitcoinj.core.integration.bitcoincore`)
* Once Debian supports a new-enough Gradle we can merge the `core` subproject and the junit5-based test-only subproject back into a single subproject.

So I propose we name the new module `core-test-junit5` and then then figure out what "source sets", Java packages, and tags/flags to use to break the tests down into subsets.

**Comment by msgilligan** [comment]
@schildbach still thinking about improving our tests... Did you ever read https://github.com/bitcoinj/bitcoinj/issues/1984#issuecomment-684043395 ?

We're still being held back by our need to support medieval Gradle for Debian. I'm wondering if we can use our regular progressive-enhancement approach and apply it to testing. This would mean _official_ Debian builds would not run _all_ tests, though we still be able to run all tests on Debian with a newer Gradle version. Do you think this approach would be acceptable?

**Comment by msgilligan** [comment]
PR #2381 has been merged, so we now have an `integration-test` subproject that uses JUnit 5 & Java 11 (and currently requires Gradle 4.6+)

In the discussion of PR #2381 @schildbach suggests:

> Maybe we'll need some instructions on how to skip integration tests, once we've added those that are unreliable.

I found this stack overflow comment with some possible methods for doing this: https://stackoverflow.com/a/34092181/420739

**Comment by schildbach** [comment]
Out of the mentioned methods, I would prefer those that do not add more conditionals to the project build files. So basically use Gradle `-x`. I think for now it's fine (maybe even intended) to run the integration tests by default.

**Comment by msgilligan** [comment]
Resolving Issue #2436 seems like a reasonable "next step" in this saga.
