### ISSUE TITLE
Upgrade build to use JDK 11

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#2149]
I've been studying the build, doing a little bit of research, and working on several pull requests. I think it's time to upgrade the build to fully take advantage of JDK 11, which means _requiring_ JDK 11 or later for the build.

 **Debian Gradle** 4.4.1 will **continue to work** (because it has a patched version of Gradle 4.4.1 that works with JDK 11) , but other platforms will require Gradle 4.10 and later .
 
This is implemented by PR #2142 which has been rebased and is ready to merge.

**Advantages**:

* Can still build JARs that target earlier JDKs: e.g. JDK 8 and JDK 7
* Can use the compiler `options.release` feature to verify modules not using Java SE APIs that are newer than target JDK.  (Using the `sourceCompatibility` and `targetCompatibility` options only enforces language features and Java bytecode versions. We've been relying on testing and a TravisCI job that builds with JDK 7 to detect use of newer APIs)
* HTML5 JavaDoc with improvements and bug fixes (see for example Issue #1870) 
* Will simplify `settings.gradle` by removing the conditional before building `wallettemplate`
* Will work on **Debian** using the default JDK (JDK 11 is the default Debian JDK since Debian 10 aka "Buster")

**Disadvantages**:

* There are some older platforms where JDK 11 is not built-in or easily installed (although I doubt any developers are building using any of these platforms in 2021)

**Gradle and CI Improvements**:

All of the PRs necessary for implementation are available, including improvements to our Gradle and CI that do the following:

* Verify that were Java SE APIs are not being used in JDK 8 or JDK 7 target JARs.
* Run tests with the target JDKs (when Gradle 6.7 or later is used)
* Verify the build on Debian Bullseye using only core packages and no binary downloads.

**Implementation PRs**:

The PRs are listed in the order in which they should be merged. (They need review and some will need rebasing after others are merged.)

- [x] PR #2140 (not technically required for JDK 11)
- [x] PR #2112 (not technically required for JDK 11)
- [x] PR #2146 (not required, but adds build & test directly on **Debian Bullseye**)
- [x] PR #2142 (Implements `options.release` and `testOnJdk7`/`testOnJdk8` tasks -- will need squash/rebase) 

**Related Issues**:

* Issue #1870
* Issue #2136
* Issue #2144 (or PR #2151)
* Issue #2145

**Comment by schildbach** [comment]
Thanks for your thorough research and assessment of the pros and cons. I agree this is a much needed step.

When I looked at this upgrade almost 2 years ago, from my memory there were two reasons why I stayed on OpenJDK8 for now:

* Building on OpenJDK11 yielded scary warnings
* And indeed, other platforms are forced to use later Gradle versions, which are then not compatible to the current configuration of the Bitcoin Wallet project, more specifically the version of the Gradle Android Plugin

I realize both of these reasons should not be an impediment to bitcoinj. Rather, they are mainly just personal inconveniences.

I'm away for a few days, but I promise I will look into upgrading my system to OpenJDK11 next week. I hope it works well enough to bridge the gap until the Kotlin/Gradle knot is finally untied.

**Comment by msgilligan** [comment]
> When I looked at this upgrade almost 2 years ago … I stayed on OpenJDK8

2 years ago JDK 8 was clearly the best choice.

> they are mainly just personal inconveniences.


> I'm away for a few days, but I promise I will look into upgrading my system to OpenJDK11 next week.

(If you're on macOS or Linux) I find that https://sdkman.io minimizes the pain of managing multiple JDKs and Gradle installs.  

(My default Java these days is JDK 16 (and soon hopefully will be JDK 17)  My default Gradle is 7.0.2. I'm able to build most projects I currently work on with JDK 16 and `./gradlew`. For **bitcoinj** I just use my default `gradle`. For projects that won't build with newer JDK or where I'm doing an "official" build with an earlier JDK, I use `sdk use` to switch the JDK)

>  I hope it works well enough to bridge the gap until the Kotlin/Gradle knot is finally untied.

I think it will work well. Even if the Kotlin/Gradle knot is untied soon, we should probably stick with JDK 11 for a while. Being able to use newer versions of Gradle, however, will give us many advantages. (I looked at the project that's porting Kotlin and Gradle to Debian, but it looks like something too big for me to help out on in my "spare" time.)

> I'm away for a few days

Hopefully, you are going to get a nice rest/vacation. Either way: Best Wishes!

**Comment by schildbach** [comment]
I'm now confident we should do this. I propose to switch the build requirement from JDK 8 to JDK 11 **as one of the very first actions in the 0.17 cycle**. Rationale for the timing: For 0.16, we won't gain anything as it will receive more or less only small patches. 0.16 *can* build with JDK 11 and 17, so developers will not need to switch JDKs if they switch release branches during the 0.17 cycle.

**Comment by kibertoad** [comment]
Would you like any help with this?

**Comment by msgilligan** [comment]
> Would you like any help with this?

Thanks for the offer. I wish I had seen this sooner!

**Comment by msgilligan** [comment]
This was completed with a2cf303655f4d1794af52a70072bc29e5a96b842 and bd6e1c6a09fe44efacb7cb7dfbee392b30da5664 takes advantage of JDK 11 and Gradle's Java Toolchains to (optionally, but used in CI) run tests on JDK 8.

**Comment by msgilligan** [comment]
@schildbach shared this blog article with me recently: https://jakewharton.com/build-on-latest-java-test-through-lowest-java/

It describes a very similar, but slightly more aggressive (i.e. uses latest version, not JDK 11 and tests with all supported previous JDKs) approach. I thought I'd just add the link here for future reference.
